import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Tools & Status',
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'Debrid Vault',
          href: 'https://debridvault.elfhosted.com/',
        },
        {
          type: 'link',
          label: 'YT Music Converter',
          href: 'https://yt.bashar.wiki/',
        },
        {
          type: 'link',
          label: 'Status Page',
          href: 'https://status.bashar.wiki/status/dves',
        },
      ],
    },
  ],
};

export default sidebars;